name: "Update D-n Labels"
description: "Automatically updates labels based on the D-n rule."
branding:
  icon: "calendar"
  color: "red"
inputs:
  token:
    description: "GitHub token"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
